### ISSUE TITLE
ModtheSpire: Save and Exit bug

### ISSUE THREAD

**Issue by Meow-Mixer** [gskleres/FruityMod-StS#182] opened 2018-04-15 00:39 UTC
If you try to save and exit with an active mod it moves to a black screen with only the mouse showing. When you try to load the game with the same mod you exited with it shows the same black screen after the megacrit intro. It only stops if you disable the mod that you were using when it happened. It has currently disabled two of my class mods because I didn't notice what was happening the first time.

**Comment by fiiiiilth** [comment] 2018-05-14 20:55
@Meow-Mixer Make sure to update ModTheSpire, BaseMod and FruityMod to their most recent versions. Everything should be working up to Weekly Patch 24, and I have been unable to reproduce this issue.

**Comment by fiiiiilth** [comment] 2018-05-17 16:35
Closing this issue. Feel free to open more if you have any other issues, but as I said, I couldn't reproduce this. Moreover, if this bug affected multiple class mods, I'd assume it's unlikely that it's specific to Fruitymod.

**Closed by fiiiiilth** 2018-05-17 16:35 UTC
