### ISSUE TITLE
Exception error on Stardust

### ISSUE THREAD

**Issue by Lunaraia** [gskleres/FruityMod-StS#133] opened 2018-03-07 00:46 UTC
This happened when it tried to just speedily drop stardust onto the board to hit Vagavhulain or whatever you call that hermit crab Elite in act 1:

Exception: java.lang.ClassCastException: com.megacrit.cardcrawl.rooms.EventRoom cannot be cast to com.megacrit.cardcrawl.rooms.MonsterRoom
01:43:58.411 ERROR core.CardCrawlGame> Exception caught
java.lang.ClassCastException: com.megacrit.cardcrawl.rooms.EventRoom cannot be cast to com.megacrit.cardcrawl.rooms.MonsterRoom
	at fruitymod.cards.Starburst.use(Starburst.java:44) ~[FruityMod.jar:?]
	at com.megacrit.cardcrawl.characters.AbstractPlayer.useCard(AbstractPlayer.java:751) ~[?:?]
	at com.megacrit.cardcrawl.actions.GameActionManager.getNextAction(GameActionManager.java:244) ~[?:?]
	at com.megacrit.cardcrawl.actions.GameActionManager.update(GameActionManager.java:135) ~[?:?]
	at com.megacrit.cardcrawl.rooms.AbstractRoom.update(AbstractRoom.java:241) ~[?:?]
	at com.megacrit.cardcrawl.rooms.EventRoom.update(EventRoom.java:51) ~[desktop-1.0.jar:?]
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.update(AbstractDungeon.java:2435) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:782) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:374) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126) [desktop-1.0.jar:?]
Game closed.

Might be caused by me not targeting something specific just dragging it out onto the field and dropping it

**Comment by daviscook477** [comment] 2018-03-07 00:47
By chance did you get that elite when you did the no pants event

**Comment by daviscook477** [comment] 2018-03-07 00:48
It's the one where you can rummage with a chance of fighting an elite

**Comment by Lunaraia** [comment] 2018-03-07 00:48
as a matter of fact, I did

**Comment by daviscook477** [comment] 2018-03-07 00:50
yeah I thought that because the issue is it's trying to cast an EventRoom to a MonsterRoom... this issue probably affects more cards than Starburst

**Comment by daviscook477** [comment] 2018-03-07 00:52
I `grep`ed the source code an apparently it **is** only Starburst that's affected by this

**Comment by daviscook477** [comment] 2018-03-07 00:52
Source code for FruityMod that is

**Comment by daviscook477** [comment] 2018-03-07 00:57
Fixed with https://github.com/gskleres/FruityMod-StS/releases/tag/v0.5.5

**Closed by daviscook477** 2018-03-07 00:57 UTC
Labels: bug
